---
- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes
  tags: [nginx, install]

- name: copy nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  become: yes
  tags: [nginx]

- name: copy nginx index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify:
    - restart nginx
  become: yes
  when: cowsay_server_name is defined
  tags: [nginx]
