- hosts: webservers 

  tasks: 
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes
      tags: [git, install]

    - name: install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes
      become: yes
      tags: [nodejs, install]

    - name: add user tirion
      ansible.builtin.user:
        name: tirion
        comment: Tirion Lannister
      become: yes
      tags: [users]

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes
      tags: [nginx, install]

    - name: copy nginx config
      ansible.builtin.copy:
        src: files/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: 
          - restart nginx
      become: yes
      tags: [nginx]

    - name: copy nginx index.html
      ansible.builtin.copy:
        src: files/nginx/index.html
        dest: /usr/share/nginx/html/index.html
      notify:
          - restart nginx
      become: yes
      tags: [nginx]

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
